name: kl_autoencoder
model_task: image_generation
cache_dir: ${oc.env:TORCH_FUSION_CACHE_DIR}/pretrained/
pretrained: True
checkpoint: null
checkpoint_state_dict_key: model
convert_bn_to_gn: false
config:
  return_dict: True
  hf_name: stabilityai/sdxl-vae