defaults:
  - /default_args/general_args@args.general_args: default # we map /default_args/general_args -> /args/general_args to keep it clean, simialrly all other default args
  - /default_args/data_loader_args@args.data_loader_args: default
  - /default_args/train_val_sampler@args.train_val_sampler: null # random_split, stratified_split, etc
  - /default_args/train_preprocess_augs@args.train_preprocess_augs: null
  - /default_args/eval_preprocess_augs@args.eval_preprocess_augs: null
  - /default_args/train_realtime_augs@args.train_realtime_augs: null
  - /default_args/eval_realtime_augs@args.eval_realtime_augs: null
  - /default_args/training_args@args.training_args: default
  - /args/data_args: "???"
  - /args/model_args: "???"
  - _self_

hydra:
  run:
    dir: ${args.general_args.root_output_dir}/run/${args.model_args.model_task}/${args.training_args.experiment_name}/${args.data_args.dataset_name}_${resolve_dir_name:${args.model_args.model_directory_name}}/${dir_name_from_overrides:${hydra.overrides},${dir_name_filter}}
  sweep:
    dir: ${args.general_args.root_output_dir}/multirun/${args.model_args.model_task}/${args.training_args.experiment_name}
    subdir: ${args.data_args.dataset_name}_${args.model_args.name}_${resolve_dir_name:${args.model_args.config.model_type}}/${dir_name_from_overrides:${hydra.overrides}}
  output_subdir: hydra
  job:
    chdir: False

# data loader args
args:
  general_args:
    do_train: ${do_train}
    do_val: ${do_val}
    do_test: ${do_test}
  data_args:
    dataset_config_name: ${dataset_config_name}
  data_loader_args:
    per_device_train_batch_size: ${per_device_train_batch_size}
    per_device_eval_batch_size: ${per_device_eval_batch_size}
    dataloader_num_workers: ${dataloader_num_workers}
  training_args:
    experiment_name: ${experiment_name}
    max_epochs: ${max_epochs}
    test_run: ${test_run}
    eval_on_start: True
    eval_every_n_epochs: 1

# general args
do_train: True
do_val: True
do_test: True

# data args
dataset_config_name: default
image_size_x: 224
image_size_y: 224

# necessary dataloader args
per_device_train_batch_size: '???'
per_device_eval_batch_size: '???'
dataloader_num_workers: '???'

# necessarytraining args
experiment_name: '???'
max_epochs: '???'
test_run: '???'

# here we map each override argument to output directory. This allows clean output directory structure for different arguments passed when sweeping for example
dir_name_filter: 
  image_size_x: sx
  image_size_y: sy
  max_epochs: epochs