# @package _global_
defaults:
  - /args/data_args: "???"
  - /args/model_args: "???"
  - override /args/data_args/train_preprocess_augs: null
  - override /args/data_args/eval_preprocess_augs: null
  - override /args/data_args/train_realtime_augs: basic
  - override /args/data_args/eval_realtime_augs: basic
  - override /args/data_args/train_val_sampler: random_split

args:
  general_args:
    do_train: ${do_train}
    do_val: ${do_val}
    do_test: ${do_test}
  training_args:
    experiment_name: cifar10_rain
    max_epochs: 10
    eval_on_start: True
    eval_every_n_epochs: 1
    test_run: False
  data_args:
    dataset_config_name: ${dataset_config_name}
    cache_file_name: ${preprocess_image_size_x}x${preprocess_image_size_y}
    data_loader_args:
      per_device_train_batch_size: 32
      per_device_eval_batch_size: 32

dataset_config_name: default
image_size_x: 224
image_size_y: 224
preprocess_image_size_y: 1024
preprocess_image_size_x: 1024
do_train: True
do_val: True
do_test: True