# @package _global_
defaults:
  - /args/data_args: "???"
  - /args/model_args: transformers/layoutlmv3

args:
  general_args:
    do_train: ${do_train}
    do_val: ${do_val}
    do_test: ${do_test}
  training_args:
    experiment_name: token_classification_${segment_level_layout}_ema={model_ema_args.enabled}_seq_128
    max_epochs: 100
    eval_on_start: True
    eval_every_n_epochs: 1
    test_run: False
    # use_ema_for_val: True
    # model_ema_args:
    #   enabled: true
    #   momentum: 0.0001
    #   update_every: 1
      # momentum_warmup: 0.999 # start from online model
      # warmup_iters: 1000
  data_args:
    cache_file_name: default_${segment_level_layout}_128
    dataset_kwargs:
      segment_level_layout: ${segment_level_layout}
      tokenizer_config: 
        name: HuggingfaceTokenizer
        kwargs: 
          model_name: microsoft/layoutlmv3-base
          init_kwargs:
            local_files_only: False
            add_prefix_space: True
            do_lower_case: false
          call_kwargs:
            add_special_tokens: True
            padding: "max_length"
            truncation: True
            max_length: 128
            stride: 0
            pad_to_multiple_of: 8
          # post processing padding args
          padding_required: True
          padding_side: right
    train_realtime_augs:
      - name: BasicImageAug
        kwargs:
          gray_to_rgb: True
          normalize: True
          rescale_strategy:
            name: Rescale
            kwargs:
              size:
                - ${realtime_image_size_x}
                - ${realtime_image_size_y}
          key:
            - image
    eval_realtime_augs:
      - name: BasicImageAug
        kwargs:
          gray_to_rgb: True
          normalize: True
          rescale_strategy:
            name: Rescale
            kwargs:
              size:
                - ${realtime_image_size_x}
                - ${realtime_image_size_y}
          key:
            - image
    data_loader_args:
      per_device_train_batch_size: 4
      per_device_eval_batch_size: 4
      dataloader_drop_last: False
      shuffle_data: True
      pin_memory: True
      dataloader_num_workers: 8
      use_test_set_for_val: False

realtime_image_size_x: 224
realtime_image_size_y: 224
do_train: True
do_val: True
do_test: False
segment_level_layout: True