per_device_train_batch_size: 4
per_device_eval_batch_size: 4
dataloader_drop_last: False
shuffle_data: True
pin_memory: True
dataloader_num_workers: 8
use_test_set_for_val: False
train_batch_sampler:
  name: ""
  kwargs: {}
eval_batch_sampler:
  name: ""
  kwargs: {}
max_test_samples: null
max_train_samples: null
max_val_samples: null